CC=gcc
CFLAGS=-I.
DIR=/Users/macbookpro/Dropbox/sight_reduction_program/makefile/

main.o: ${DIR}lib.c ${DIR}main.c
	$(CC) -o main.o ${DIR}lib.c ${DIR}main.c

clean:
	echo "I am cleaning everything!"
	rm -rf *.o
