CXX=g++
CFLAGS=-I.
DIR=/Users/macbookpro/Dropbox/sight_reduction_program/makefile/

main.o: lib.cpp main.cpp
	$(CXX) -o main.o ${DIR}lib.cpp ${DIR}main.cpp

clean:
	echo "I am cleaning everything!"
	rm -rf *.o
